cluster.name: vagrant-elastic-clusters
node.name: master
node.master: true
node.data: false

path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch

network.host: [_local_, _site_]

discovery.seed_hosts: ["10.0.0.10"]

cluster.initial_master_nodes: ["master"]

node.ml: false
node.ingest: false
